application: ${app_id}
version: 1
runtime: python27
api_version: 1

builtins:
- appstats: on
- remote_api: on

inbound_services:
- warmup

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
#- ^media/.*

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.ui.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /static
  static_dir: static

- url: /media
  static_dir: _generated_media
  expiration: '365d'

- url: /.*
  script: djangoappengine.main.main.application
